### PR TITLE
Adding more flexible rust version

### PR DESCRIPTION
**Pull request by Grummfy**
Hello,
I try to add the possibility to build rust with the rustup.sh utility. this allow to us both version and stable|beta|nightly version of rust.

So if you are intrested, just tell me and I will adapt the README.md and Dockerfile to this repository.

Thanks

### CODE REVIEW

**Comment by jimmycuadra** [comment]
How are you imagining the channels would be updated? What triggers a new nightly Docker image? How does the end user determine which version of Rust the channel-tagged image actually is?

**Comment by Grummfy** [comment]
As I know there is no way to automatically build this. For now, I thing there is no good solution (we can't send env variable with webhook trigger), but it's like you now, you need to manually update it. We can image adding a build script for stable/nightly/beta and the last revision. and running this script manually.

**Comment by jimmycuadra** [comment]
I think without a way of automating the releases of new versions, I don't want to change my image to work this way. Thanks for bringing it up, though. There is a definite need for a set of Docker images for Rust with more flexibility on the version.

**Comment by Grummfy** [comment]
thanks to look at it

**Pull request closed without merging**
